### PR TITLE
Add mulch and vanadium system webview and upgraded some stuff

### PR DESCRIPTION
**Pull request by GitGitro**
Added mulch system webview

Updated:
- agp
- sdk target and compile
- jvm

### CODE REVIEW

**Comment by neoblackxt** [comment]
Thank you for submitting your pull request. I appreciate your contribution to our project.

After reviewing your changes, I think the functionality you added is useful for a small group of users. However, I believe it would be better to make the feature more flexible by adding a GUI that allows users to customize their settings. This would make the feature more accessible and easier to use for everyone.

I understand that this will require additional work, but I believe it will improve the overall user experience. Would you be willing to work on adding a GUI for this feature? If not, I would be happy to work on it myself.

Thank you again for your contribution, and I look forward to hearing your thoughts on this matter.

**Comment by selurvedu** [comment]
Wouldn't it be better to accept the simple solution that already works now while the GUI is not available yet?

Many users will benefit from this since Bromite WebView has not seen any updates for a while (since Dec 20). Mulch WebView seems to be a viable alternative.

**Comment by moriel5** [comment]
Hmm... This may be a stretch, since I am not sure if the necessary code is in place, however running GeckoView (only available as source code meant for implementing in browsers, however it with interest is displayed, perhaps someone will build a standalone module) or Firefox as the default web engine in place of WebView (if Chrome can be set as default, theoretically Firefox should be possible as well, discounting possible bugs due to the unexpected libraries) would be nice.

That, and if this option existed, it could pave the way for custom ROMs to start bundling GeckoView instead of WebView.

I should try asking the developer of SmartCookieWeb if he is interested in getting his Gecko-based browser seen as a valid system web engine with this XPosed module. Perhaps a test APK could give some more insight.

**Comment by Venderbad** [comment]
> if Chrome can be set as default, theoretically Firefox should be possible as well, discounting possible bugs due to the unexpected libraries

Might be possible but quite hard to realize, see [this](https://github.com/mozilla/geckoview/issues/167).

**Comment by moriel5** [comment]
@Venderbad Thanks for the reply and the link.

Yup, that conversation pretty much sums up my concerns about compatibility, however also supports my opinion that if we have this option, it could help debugging and could pave the way for eventually being realistic for standard users as well.

If it does technically work, I would recommend putting it behind a flag that explicitly points it out as being for testing purposes only, at least until future viability could be assumed.

**Comment by xplshn** [comment]
A GUi? For what?

**Comment by Venderbad** [comment]
> A GUi? For what?

I guess probably to have a inputbox where you can type in the package name of the webview apk and dynamically add that webview to the selectable webview implementation list?

**Comment by xplshn** [comment]
You'd still need to add the package signature. Focus on just adding Mulch, and Vanadium, just have to merge this. There aren't more Android Webviews than this anyways. K.I.S.S Philosophy is always better than GUIs, also, people who have Xposed on their phones, don't need user friendly, graphical user interfaces, you need Magisk, or Riru anyways, so... Kinda useless to try and be user friendly.

**Comment by Venderbad** [comment]
Got your point bro, the whole thing is in fact a choice between expandability and the KISS principle.
> There aren't more Android Webviews than this anyways.

And this is true for now. I assume it will remain true for quite a lengthy period. We can now wait to see how @neoblackxt  intends to do it.

**Comment by xplshn** [comment]
Thanks bro, you're awesome!

**Comment by xplshn** [comment]
@GitGitro Can you justo fork this? I don't think the dev cares too much, I'm waiting for you to release a signed build. :)

**Comment by neoblackxt** [comment]
A comprehensive and thorough solution will be provided.

**Pull request closed without merging**
